Capstone projecct 1
AbigiyaTY/Empowering-African-Women pull request #1
Opened 2022-08-04 20:31 UTC by AbigiyaTY

# African women empowerment website

For this project I:

- Build the skeleton of the body using HTML
- Add styling using CSS and bootstrap 5
- Create the speaker section dynamical and the hamburger menu responsive using javascript.
- Made the website Accessibly

2022-08-04 21:55 UTC, rloterh requested changes
Hi Abigail, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there! 🚦 🚦 🚦  

## Highlights 👍  
- Good presentation of project
- Nice job to acknowledge [Cindy Shin](https://www.behance.net/adagio07)
- Correctly implemented navigation menu
- Mobile menu works seamlessly
- Implemented HTML 5 semantics properly



## Required Changes ♻️
_Kindly check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly check the comments marked **[OPTIONAL]** under the review._

You can also consider:
- N/A

<br>
Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-04 21:55 UTC, rloterh commented on README.md
> +[Live Demo Link](/)
No link has been provided for the live demo in your ReadMe, and hence it's displaying as 404. Kindly ensure that:
- [ ] The web pages are deployed using **GitHub Pages**.
- [ ] The project is **deployed properly**, all pages, links, and images work as expected.
- [ ] A **link to the deployed project is present** in the README.

2022-08-04 21:55 UTC, rloterh commented on about.html
> +            <i class="mt-5 hamburger-menu openMenu fa fa-bars"></i>
[ ] OPTIONAL
To improve the **user experience** it will be good practice to ensure that the _hamburger_ and the _close button_ are behaving as buttons when the mouse hovers on them. We can improve upon this aspect by adding the CSS attribute `cursor: pointer` to the _hamburger_ and the _close button_ on _mouse hover_ events. We can additionally change the color or opacity of these objects during the hover event.

2022-08-04 21:55 UTC, rloterh commented on about.html
> +            <ul class="row header2List mainMenu">
Your mobile menu works seamlessly, however, the background picture it too opaque which makes the menu item on the mobile menu not to standout clearly. You have two options here:
- [ ] You can make it's background transparent, or
- [ ]  Make it the same color/pattern as the top section background

2022-08-04 21:55 UTC, rloterh commented on about.html
> +    <section class="bodyHeader container">
The contents your page for desktop versions needs some alignments. Kindly note that we as much as possible want our design to closely mimic the provide [design template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015), therefore kindly improve upon the following aspect of alignment: of your design:
- [ ] The contents of the hero section should be aligned to the left together with the logo 
- [ ] The right part (the rectangle with red thick border) of the white navbar should be aligned to the right together with logout text on the dark navbar 

**Your design:**
![image](https://user-images.githubusercontent.com/12745474/182956414-af34ec61-842d-4998-bfda-fb65a9759a15.png)


**The original design:**
![image](https://user-images.githubusercontent.com/12745474/182956688-bb1e07e8-9b0f-4702-8b76-e133fad27940.png)

2022-08-04 21:55 UTC, rloterh commented on about.html
> +              >Join<span class="navSpanArrow3">></span></a
- [ ] The call to action white text under the _main program_ section should be in **block letters**. Kindly ensure to improve upon this aspect.

2022-08-04 21:55 UTC, rloterh commented on index.html
> +        <div class="headerDate">2022.08.11(THU) ~ 12(FRI)</div>
- [ ] Kindly make the date under this section a bit bolder, as can be seen in the [design template](https://www.behance.net/gallery/29845175/CC-Global-Summit-2015).

2022-08-05 12:13 UTC, prolajumokeoni approved these changes
Hi @AbigiyaTY, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- No linter errors ✅ 
- Git flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-05 12:18 UTC, merged